services:
  - type: web
    name: sambal-gesek-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js

  - type: cron
    name: inventory-snapshot
    env: node
    schedule: "5 0 1 * *"
    buildCommand: npm install
    startCommand: node src/jobs/inventorySnapshotJob.js