services:
  - type: web
    name: sambal-gesek-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js

cronJobs:
  - type: cron
    name: inventory-snapshot
    env: node
    schedule: "0 0 * * *"
    buildCommand: npm install
    startCommand: node src/jobs/inventorySnapshotJob.js