module.exports = {
  IN: require("../handlers/in"),
  OUT: require("../handlers/out"),
  ADDITEM: require("../handlers/addItem"),
  REMOVEITEM: require("../handlers/removeItem"),
  LIST: require("../handlers/list"),
  STOCK: require("../handlers/stock"),
  APPROVE: require("../handlers/approve"),
  REJECT: require("../handlers/reject"),
  REPORT: require("../handlers/report"),
  HELP: require("../handlers/help"),
  STAFF: require("../handlers/staff"),
  LOG: require("../handlers/log"),
  ITEM: require("../handlers/item"),
  SETROLE: require("../handlers/setRole"),
  REMOVEROLE: require("../handlers/removeRole"),
  REMOVEOUTLET: require("../handlers/removeOutlet"),
  UPDATE: require("../handlers/update"),
  REACTIVATE: require("../handlers/reactivate"),
  REPORTMENU: require("../handlers/reportMenu"),
  REPORT_MONTH: require("../handlers/reportMonth"),
  PENDING: require("../handlers/pending"),
  UPITEM: require("../handlers/updateItem"),
  WASTAGE: require("../handlers/wastage"),
  TRY: require("../handlers/try")
};